name: Joey Zolfaghari
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5818
title: Community Manager
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d3e7f9'
    - '#4c87c3'
    - '#374e3e'
    - '#6a7656'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
