name: Joey Zolfaghari
favicon: null
layout_spectrum: 0.8847784630488604
typography_spectrum: 0.5482708376366645
title: Community Manager
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f7'
    - '#000000'
    - '#999999'
    - '#b30711'
    - '#545454'
  brandStrength: 0.9375
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
