name: Joey Zolfaghari
favicon: null
layout_spectrum: 0.8847784630488604
typography_spectrum: 0.5482708376366645
title: Community Manager
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.666541087673977
  lightness: 0.7363958391360939
  saturation: 0.22496156743727624
  rhythmicContrast: 0.9053835936356336
purpose: []
