name: Joey Zolfaghari
favicon: null
layout_spectrum: 0.48832
typography_spectrum: 0.5818
title: Community Manager
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6d6d6d'
    - '#000000'
    - '#c70813'
    - '#d95558'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
